name: x402-email-validator

services:
  email-validator:
    build: .
    container_name: x402-email-validator
    restart: unless-stopped
    ports:
      - "3036:3036"
    env_file:
      - .env
    networks:
      - traefik
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x402-email-validator.rule=Host(`x402-email-validator.suretat.com`)"
      - "traefik.http.routers.x402-email-validator.entrypoints=websecure"
      - "traefik.http.routers.x402-email-validator.tls.certresolver=letsencrypt"
      - "traefik.http.services.x402-email-validator.loadbalancer.server.port=3036"

networks:
  traefik:
    external: true
    name: traefik
  proxy:
    external: true
    name: proxy
