name: x402-pdf-generator

services:
  pdf:
    build: .
    container_name: x402-pdf-generator
    restart: unless-stopped
    ports:
      - "3041:3040"
    env_file:
      - .env
    networks:
      - traefik
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x402-pdf-generator.rule=Host(`x402-pdf.suretat.com`)"
      - "traefik.http.routers.x402-pdf-generator.entrypoints=websecure"
      - "traefik.http.routers.x402-pdf-generator.tls.certresolver=letsencrypt"
      - "traefik.http.services.x402-pdf-generator.loadbalancer.server.port=3040"

networks:
  traefik:
    external: true
    name: traefik
  proxy:
    external: true
    name: proxy
