from __future__ import annotations
import os
import time
from typing import Optional

import uvicorn
from fastapi import FastAPI, Query, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel

PRICE_ATOMIC = os.getenv("PRICE_ATOMIC", "500")
PAY_TO = os.getenv("PAY_TO", "0x6458941857a70C6cA18c440a316035A21901A12b")
NETWORK = os.getenv("NETWORK", "base")
ASSET_ADDRESS = os.getenv("ASSET_ADDRESS", "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913")

stats = {"total_paid": 0, "revenue_usdc": 0.0, "start_time": time.time()}

app = FastAPI(title="x402 NAF/APE Code Lookup", version="1.0.0")

# ── NAF 2008 Rév. 2 — nomenclature complète INSEE ──────────────────────────
# Format: "CODE": {"libelle": "...", "section": "A-U", "section_libelle": "..."}

SECTIONS = {
    "A": "Agriculture, sylviculture et pêche",
    "B": "Industries extractives",
    "C": "Industrie manufacturière",
    "D": "Production et distribution d'électricité, de gaz, de vapeur et d'air conditionné",
    "E": "Production et distribution d'eau ; assainissement, gestion des déchets et dépollution",
    "F": "Construction",
    "G": "Commerce ; réparation d'automobiles et de motocycles",
    "H": "Transports et entreposage",
    "I": "Hébergement et restauration",
    "J": "Information et communication",
    "K": "Activités financières et d'assurance",
    "L": "Activités immobilières",
    "M": "Activités spécialisées, scientifiques et techniques",
    "N": "Activités de services administratifs et de soutien",
    "O": "Administration publique",
    "P": "Enseignement",
    "Q": "Santé humaine et action sociale",
    "R": "Arts, spectacles et activités récréatives",
    "S": "Autres activités de services",
    "T": "Activités des ménages en tant qu'employeurs",
    "U": "Activités extra-territoriales",
}

NAF: dict[str, dict] = {
    # A — Agriculture
    "0111Z": ("Culture de céréales, de légumineuses et de graines oléagineuses", "A"),
    "0112Z": ("Culture du riz", "A"),
    "0113Z": ("Culture de légumes, de melons, de racines et de tubercules", "A"),
    "0114Z": ("Culture de la canne à sucre", "A"),
    "0115Z": ("Culture du tabac", "A"),
    "0119Z": ("Autres cultures non permanentes", "A"),
    "0121Z": ("Culture de la vigne", "A"),
    "0122Z": ("Culture de fruits tropicaux et subtropicaux", "A"),
    "0123Z": ("Culture d'agrumes", "A"),
    "0124Z": ("Culture de fruits à pépins et à noyau", "A"),
    "0125Z": ("Culture d'autres fruits d'arbres ou d'arbustes et de fruits à coque", "A"),
    "0126Z": ("Culture de fruits oléagineux", "A"),
    "0127Z": ("Culture de plantes à boissons", "A"),
    "0128Z": ("Culture de plantes à épices, aromatiques, médicinales et pharmaceutiques", "A"),
    "0129Z": ("Autres cultures permanentes", "A"),
    "0130Z": ("Reproduction de plantes", "A"),
    "0141Z": ("Élevage de vaches laitières", "A"),
    "0142Z": ("Élevage d'autres bovins et de buffles", "A"),
    "0143Z": ("Élevage de chevaux et d'autres équidés", "A"),
    "0144Z": ("Élevage de chameaux et d'autres camélidés", "A"),
    "0145Z": ("Élevage d'ovins et de caprins", "A"),
    "0146Z": ("Élevage de porcins", "A"),
    "0147Z": ("Élevage de volailles", "A"),
    "0149Z": ("Élevage d'autres animaux", "A"),
    "0150Z": ("Culture et élevage associés", "A"),
    "0161Z": ("Activités de soutien aux cultures", "A"),
    "0162Z": ("Activités de soutien à la production animale", "A"),
    "0163Z": ("Traitement primaire des récoltes", "A"),
    "0164Z": ("Traitement des semences", "A"),
    "0170Z": ("Chasse, piégeage et services annexes", "A"),
    "0210Z": ("Sylviculture et autres activités forestières", "A"),
    "0220Z": ("Exploitation forestière", "A"),
    "0230Z": ("Récolte de produits forestiers non ligneux poussant à l'état sauvage", "A"),
    "0240Z": ("Services de soutien à l'exploitation forestière", "A"),
    "0311Z": ("Pêche en mer", "A"),
    "0312Z": ("Pêche en eau douce", "A"),
    "0321Z": ("Aquaculture en mer", "A"),
    "0322Z": ("Aquaculture en eau douce", "A"),
    # B — Industries extractives
    "0510Z": ("Extraction de houille", "B"),
    "0520Z": ("Extraction de lignite", "B"),
    "0610Z": ("Extraction de pétrole brut", "B"),
    "0620Z": ("Extraction de gaz naturel", "B"),
    "0710Z": ("Extraction de minerais de fer", "B"),
    "0729Z": ("Extraction d'autres minerais de métaux non ferreux", "B"),
    "0811Z": ("Extraction de pierres ornementales et de construction", "B"),
    "0812Z": ("Extraction de graviers, sables et argiles", "B"),
    "0891Z": ("Extraction des minéraux chimiques et d'engrais minéraux", "B"),
    "0990Z": ("Activités de soutien aux autres industries extractives", "B"),
    # C — Industrie manufacturière (sélection)
    "1011Z": ("Transformation et conservation de la viande de boucherie", "C"),
    "1012Z": ("Transformation et conservation de la viande de volaille", "C"),
    "1013A": ("Préparation industrielle de produits à base de viande", "C"),
    "1020Z": ("Transformation et conservation de poisson", "C"),
    "1031Z": ("Transformation et conservation de pommes de terre", "C"),
    "1032Z": ("Préparation de jus de fruits et légumes", "C"),
    "1039A": ("Autre transformation et conservation de légumes", "C"),
    "1039B": ("Transformation et conservation de fruits", "C"),
    "1041A": ("Fabrication d'huiles et graisses brutes", "C"),
    "1051A": ("Fabrication de lait liquide et de produits frais", "C"),
    "1051B": ("Fabrication de beurre", "C"),
    "1052Z": ("Fabrication de glaces et sorbets", "C"),
    "1061A": ("Meunerie", "C"),
    "1071A": ("Fabrication industrielle de pain et de pâtisserie fraîche", "C"),
    "1071B": ("Cuisson de produits de boulangerie", "C"),
    "1071C": ("Boulangerie et boulangerie-pâtisserie", "C"),
    "1071D": ("Pâtisserie", "C"),
    "1072Z": ("Fabrication de biscuits, biscottes et pâtisseries de conservation", "C"),
    "1082Z": ("Fabrication de cacao, chocolat et de produits de confiserie", "C"),
    "1083Z": ("Transformation du thé et du café", "C"),
    "1084Z": ("Fabrication de condiments et assaisonnements", "C"),
    "1085Z": ("Fabrication de plats préparés", "C"),
    "1086Z": ("Fabrication d'aliments homogénéisés et diététiques", "C"),
    "1089Z": ("Fabrication d'autres produits alimentaires", "C"),
    "1101Z": ("Production de boissons alcooliques distillées", "C"),
    "1102A": ("Fabrication de vins d'appellation d'origine protégée", "C"),
    "1105Z": ("Fabrication de bière", "C"),
    "1107A": ("Industrie des eaux de table", "C"),
    "1200Z": ("Fabrication de produits à base de tabac", "C"),
    "1310Z": ("Préparation de fibres textiles et filature", "C"),
    "1320Z": ("Tissage", "C"),
    "1391Z": ("Fabrication d'étoffes à maille", "C"),
    "1393Z": ("Fabrication de tapis et moquettes", "C"),
    "1395Z": ("Fabrication de non-tissés, sauf habillement", "C"),
    "1411Z": ("Fabrication de vêtements en cuir", "C"),
    "1413Z": ("Fabrication d'autres vêtements de dessus", "C"),
    "1414Z": ("Fabrication de vêtements de dessous", "C"),
    "1419Z": ("Fabrication d'autres vêtements et accessoires", "C"),
    "1420Z": ("Fabrication d'articles en fourrure", "C"),
    "1431Z": ("Fabrication de bas et chaussettes en maille", "C"),
    "1511Z": ("Apprêt et tannage des cuirs ; préparation et teinture des fourrures", "C"),
    "1520Z": ("Fabrication de chaussures", "C"),
    "1610A": ("Sciage et rabotage du bois, hors imprégnation", "C"),
    "1621Z": ("Fabrication de placage et de panneaux de bois", "C"),
    "1622Z": ("Fabrication de parquets assemblés", "C"),
    "1623Z": ("Fabrication de charpentes et d'autres menuiseries", "C"),
    "1624Z": ("Fabrication d'emballages en bois", "C"),
    "1711Z": ("Fabrication de pâte à papier", "C"),
    "1712Z": ("Fabrication de papier et de carton", "C"),
    "1721A": ("Fabrication de carton ondulé", "C"),
    "1722Z": ("Fabrication d'articles en papier à usage sanitaire ou domestique", "C"),
    "1811Z": ("Imprimerie de journaux", "C"),
    "1812Z": ("Autre imprimerie", "C"),
    "1813Z": ("Activités de pré-presse", "C"),
    "1814Z": ("Reliure et activités connexes", "C"),
    "1820Z": ("Reproduction d'enregistrements", "C"),
    "1910Z": ("Cokéfaction", "C"),
    "1920Z": ("Raffinage du pétrole", "C"),
    "2011Z": ("Fabrication de gaz industriels", "C"),
    "2012Z": ("Fabrication de colorants et de pigments", "C"),
    "2013A": ("Enrichissement et retraitement de matières nucléaires", "C"),
    "2014Z": ("Fabrication d'autres produits chimiques organiques de base", "C"),
    "2015Z": ("Fabrication de produits azotés et d'engrais", "C"),
    "2016Z": ("Fabrication de matières plastiques de base", "C"),
    "2017Z": ("Fabrication de caoutchouc synthétique", "C"),
    "2020Z": ("Fabrication de pesticides et d'autres produits agrochimiques", "C"),
    "2030Z": ("Fabrication de peintures, vernis, encres et mastics", "C"),
    "2041Z": ("Fabrication de savons, détergents et produits d'entretien", "C"),
    "2042Z": ("Fabrication de parfums et de produits pour la toilette", "C"),
    "2051Z": ("Fabrication de produits explosifs", "C"),
    "2059Z": ("Fabrication d'autres produits chimiques n.c.a.", "C"),
    "2060Z": ("Fabrication de fibres artificielles ou synthétiques", "C"),
    "2110Z": ("Fabrication de produits pharmaceutiques de base", "C"),
    "2120Z": ("Fabrication de préparations pharmaceutiques", "C"),
    "2211Z": ("Fabrication et rechapage de pneumatiques", "C"),
    "2219Z": ("Fabrication d'autres articles en caoutchouc", "C"),
    "2221Z": ("Fabrication de plaques, feuilles, tubes et profilés en matières plastiques", "C"),
    "2222Z": ("Fabrication d'emballages en matières plastiques", "C"),
    "2223Z": ("Fabrication d'éléments en matières plastiques pour la construction", "C"),
    "2229A": ("Fabrication de pièces techniques à base de matières plastiques", "C"),
    "2310Z": ("Fabrication de verre plat", "C"),
    "2320Z": ("Façonnage et transformation du verre plat", "C"),
    "2350Z": ("Fabrication de ciments, chaux et plâtres", "C"),
    "2351Z": ("Fabrication de béton prêt à l'emploi", "C"),
    "2395Z": ("Fabrication d'articles en fibres minérales", "C"),
    "2410Z": ("Sidérurgie", "C"),
    "2420Z": ("Fabrication de tubes, tuyaux, profilés creux et accessoires en acier", "C"),
    "2431Z": ("Étirage à froid de barres", "C"),
    "2451Z": ("Fonderie de fonte", "C"),
    "2452Z": ("Fonderie d'acier", "C"),
    "2453Z": ("Fonderie de métaux légers", "C"),
    "2511Z": ("Fabrication de structures métalliques et de parties de structures", "C"),
    "2512Z": ("Fabrication de portes et fenêtres en métal", "C"),
    "2521Z": ("Fabrication de radiateurs et de chaudières pour le chauffage central", "C"),
    "2530Z": ("Fabrication de générateurs de vapeur", "C"),
    "2540Z": ("Fabrication d'armes et de munitions", "C"),
    "2591Z": ("Fabrication de fûts et emballages métalliques similaires", "C"),
    "2593Z": ("Fabrication d'articles en fils métalliques, de chaînes et de ressorts", "C"),
    "2599A": ("Fabrication d'articles métalliques ménagers", "C"),
    "2610Z": ("Fabrication de composants électroniques", "C"),
    "2620Z": ("Fabrication d'ordinateurs et d'équipements périphériques", "C"),
    "2630Z": ("Fabrication d'équipements de communication", "C"),
    "2640Z": ("Fabrication de produits électroniques grand public", "C"),
    "2651A": ("Fabrication d'équipements d'aide à la navigation", "C"),
    "2651B": ("Fabrication d'instrumentation scientifique et technique", "C"),
    "2660Z": ("Fabrication d'équipements d'irradiation médicale", "C"),
    "2670Z": ("Fabrication de matériels optique et photographique", "C"),
    "2680Z": ("Fabrication de supports magnétiques et optiques", "C"),
    "2711Z": ("Fabrication de moteurs, génératrices et transformateurs électriques", "C"),
    "2712Z": ("Fabrication de matériel de distribution et de commande électrique", "C"),
    "2731Z": ("Fabrication de câbles de fibres optiques", "C"),
    "2732Z": ("Fabrication d'autres fils et câbles électroniques ou électriques", "C"),
    "2733Z": ("Fabrication de matériel d'installation électrique", "C"),
    "2740Z": ("Fabrication de lampes et d'appareils d'éclairage", "C"),
    "2751Z": ("Fabrication d'appareils électroménagers", "C"),
    "2752Z": ("Fabrication d'appareils ménagers non électriques", "C"),
    "2790Z": ("Fabrication d'autres matériels électriques", "C"),
    "2811Z": ("Fabrication de moteurs et turbines", "C"),
    "2812Z": ("Fabrication d'équipements hydrauliques et pneumatiques", "C"),
    "2813Z": ("Fabrication d'autres pompes et compresseurs", "C"),
    "2821Z": ("Fabrication de fours et brûleurs", "C"),
    "2822Z": ("Fabrication de matériel de levage et de manutention", "C"),
    "2823Z": ("Fabrication de machines et d'équipements de bureau", "C"),
    "2824Z": ("Fabrication d'outillage portatif à moteur incorporé", "C"),
    "2825Z": ("Fabrication d'équipements aérauliques et frigorifiques industriels", "C"),
    "2829A": ("Fabrication d'équipements d'emballage, de conditionnement et de pesage", "C"),
    "2840Z": ("Fabrication de machines-outils pour le travail des métaux", "C"),
    "2849Z": ("Fabrication d'autres machines-outils", "C"),
    "2851Z": ("Fabrication de machines pour la métallurgie", "C"),
    "2852Z": ("Fabrication de machines pour l'extraction ou la construction", "C"),
    "2853Z": ("Fabrication de machines pour l'industrie agro-alimentaire", "C"),
    "2854Z": ("Fabrication de machines pour les industries textiles", "C"),
    "2899A": ("Fabrication de machines d'imprimerie", "C"),
    "2910Z": ("Construction de véhicules automobiles", "C"),
    "2920Z": ("Fabrication de carrosseries et remorques", "C"),
    "2931Z": ("Fabrication d'équipements électriques et électroniques automobiles", "C"),
    "2932Z": ("Fabrication d'autres équipements automobiles", "C"),
    "3011Z": ("Construction de navires et de structures flottantes", "C"),
    "3012Z": ("Construction de bateaux de plaisance", "C"),
    "3020Z": ("Construction de locomotives et d'autre matériel ferroviaire roulant", "C"),
    "3030Z": ("Construction aéronautique et spatiale", "C"),
    "3040Z": ("Construction de véhicules militaires de combat", "C"),
    "3091Z": ("Fabrication de motocycles", "C"),
    "3092Z": ("Fabrication de bicyclettes et de véhicules pour invalides", "C"),
    "3099Z": ("Fabrication d'autres équipements de transport n.c.a.", "C"),
    "3101Z": ("Fabrication de meubles de bureau et de magasin", "C"),
    "3102Z": ("Fabrication de meubles de cuisine", "C"),
    "3103Z": ("Fabrication de matelas", "C"),
    "3109A": ("Fabrication de sièges d'ameublement d'intérieur", "C"),
    "3109B": ("Fabrication d'autres meubles et industries connexes de l'ameublement", "C"),
    "3211Z": ("Frappe de monnaie", "C"),
    "3212Z": ("Fabrication d'articles de joaillerie et bijouterie", "C"),
    "3213Z": ("Fabrication d'articles de bijouterie fantaisie et articles similaires", "C"),
    "3220Z": ("Fabrication d'instruments de musique", "C"),
    "3230Z": ("Fabrication d'articles de sport", "C"),
    "3240Z": ("Fabrication de jeux et jouets", "C"),
    "3250A": ("Fabrication de matériel médico-chirurgical et dentaire", "C"),
    "3250B": ("Fabrication de lunettes", "C"),
    "3291Z": ("Fabrication d'articles de brosserie", "C"),
    "3299Z": ("Autres activités manufacturières n.c.a.", "C"),
    "3311Z": ("Réparation d'ouvrages en métaux", "C"),
    "3312Z": ("Réparation de machines et équipements mécaniques", "C"),
    "3313Z": ("Réparation de matériels électroniques et optiques", "C"),
    "3314Z": ("Réparation d'équipements électriques", "C"),
    "3315Z": ("Réparation et maintenance navale", "C"),
    "3316Z": ("Réparation et maintenance d'aéronefs et d'engins spatiaux", "C"),
    "3317Z": ("Réparation et maintenance d'autres équipements de transport", "C"),
    # D — Électricité, gaz
    "3511Z": ("Production d'électricité", "D"),
    "3512Z": ("Transport d'électricité", "D"),
    "3513Z": ("Distribution d'électricité", "D"),
    "3514Z": ("Commerce d'électricité", "D"),
    "3521Z": ("Production de combustibles gazeux", "D"),
    "3522Z": ("Distribution de combustibles gazeux par conduites", "D"),
    "3523Z": ("Commerce de combustibles gazeux par conduites", "D"),
    "3530Z": ("Production et distribution de vapeur et d'air conditionné", "D"),
    # E — Eau, déchets
    "3600Z": ("Captage, traitement et distribution d'eau", "E"),
    "3700Z": ("Collecte et traitement des eaux usées", "E"),
    "3811Z": ("Collecte des déchets non dangereux", "E"),
    "3812Z": ("Collecte des déchets dangereux", "E"),
    "3821Z": ("Traitement et élimination des déchets non dangereux", "E"),
    "3822Z": ("Traitement et élimination des déchets dangereux", "E"),
    "3831Z": ("Démantèlement d'épaves", "E"),
    "3832Z": ("Récupération de déchets triés", "E"),
    "3900Z": ("Dépollution et autres services de gestion des déchets", "E"),
    # F — Construction
    "4110A": ("Promotion immobilière de logements", "F"),
    "4110B": ("Promotion immobilière de bureaux", "F"),
    "4110C": ("Promotion immobilière d'autres bâtiments", "F"),
    "4110D": ("Supports de droits de construire", "F"),
    "4120A": ("Construction de maisons individuelles", "F"),
    "4120B": ("Construction d'autres bâtiments résidentiels", "F"),
    "4211Z": ("Construction de routes et autoroutes", "F"),
    "4212Z": ("Construction de voies ferrées de surface et souterraines", "F"),
    "4213A": ("Construction d'ouvrages d'art", "F"),
    "4213B": ("Construction et entretien de tunnels", "F"),
    "4221Z": ("Construction de réseaux pour fluides", "F"),
    "4222Z": ("Construction de réseaux électriques et de télécommunications", "F"),
    "4291Z": ("Construction d'ouvrages maritimes et fluviaux", "F"),
    "4299Z": ("Construction d'autres ouvrages de génie civil n.c.a.", "F"),
    "4311Z": ("Travaux de démolition", "F"),
    "4312A": ("Travaux de terrassement courants et travaux préparatoires", "F"),
    "4312B": ("Travaux de terrassement spécialisés ou de grande masse", "F"),
    "4313Z": ("Forages et sondages", "F"),
    "4321A": ("Travaux d'installation électrique dans tous locaux", "F"),
    "4321B": ("Travaux d'installation électrique sur la voie publique", "F"),
    "4322A": ("Travaux d'installation d'eau et de gaz en tous locaux", "F"),
    "4322B": ("Travaux d'installation d'équipements thermiques et de climatisation", "F"),
    "4329A": ("Travaux d'isolation", "F"),
    "4329B": ("Autres travaux d'installation n.c.a.", "F"),
    "4331Z": ("Travaux de plâtrerie", "F"),
    "4332A": ("Travaux de menuiserie bois et PVC", "F"),
    "4332B": ("Travaux de menuiserie métallique et serrurerie", "F"),
    "4332C": ("Agencement de lieux de vente", "F"),
    "4333Z": ("Travaux de revêtement des sols et des murs", "F"),
    "4334Z": ("Travaux de peinture et vitrerie", "F"),
    "4339Z": ("Autres travaux de finition", "F"),
    "4391A": ("Travaux de charpente", "F"),
    "4391B": ("Travaux de couverture par éléments", "F"),
    "4399A": ("Travaux d'étanchéification", "F"),
    "4399B": ("Travaux de montage de structures métalliques", "F"),
    "4399C": ("Travaux de maçonnerie générale et gros œuvre de bâtiment", "F"),
    "4399D": ("Autres travaux spécialisés de construction", "F"),
    "4399E": ("Location avec opérateur de matériel de construction", "F"),
    # G — Commerce
    "4511Z": ("Commerce de voitures et de véhicules automobiles légers", "G"),
    "4519Z": ("Commerce d'autres véhicules automobiles", "G"),
    "4520A": ("Entretien et réparation de véhicules automobiles légers", "G"),
    "4520B": ("Entretien et réparation d'autres véhicules automobiles", "G"),
    "4531Z": ("Commerce de gros d'équipements automobiles", "G"),
    "4532Z": ("Commerce de détail d'équipements automobiles", "G"),
    "4540Z": ("Commerce et réparation de motocycles", "G"),
    "4611Z": ("Agents spécialisés dans le commerce de gros de matières premières agricoles et d'animaux vivants", "G"),
    "4619A": ("Centrales d'achat alimentaires", "G"),
    "4619B": ("Autres intermédiaires du commerce en produits divers", "G"),
    "4621Z": ("Commerce de gros de céréales, de tabac non manufacturé, de semences et d'aliments pour le bétail", "G"),
    "4632A": ("Commerce de gros de viandes de boucherie", "G"),
    "4639A": ("Commerce de gros de produits laitiers, œufs, huiles et matières grasses comestibles", "G"),
    "4639B": ("Commerce de gros alimentaire spécialisé divers", "G"),
    "4641Z": ("Commerce de gros de textiles", "G"),
    "4642Z": ("Commerce de gros d'habillement et de chaussures", "G"),
    "4643Z": ("Commerce de gros d'appareils électroménagers", "G"),
    "4644Z": ("Commerce de gros de vaisselle, verrerie et produits d'entretien", "G"),
    "4645Z": ("Commerce de gros de parfumerie et de produits de beauté", "G"),
    "4646Z": ("Commerce de gros de produits pharmaceutiques", "G"),
    "4647Z": ("Commerce de gros de meubles, de tapis et d'appareils d'éclairage", "G"),
    "4648Z": ("Commerce de gros d'articles d'horlogerie et de bijouterie", "G"),
    "4651Z": ("Commerce de gros d'ordinateurs, d'équipements informatiques périphériques et de logiciels", "G"),
    "4652Z": ("Commerce de gros de composants et d'équipements électroniques et de télécommunication", "G"),
    "4661Z": ("Commerce de gros de matériel agricole", "G"),
    "4662Z": ("Commerce de gros de machines-outils", "G"),
    "4663Z": ("Commerce de gros de machines pour l'extraction, la construction et le génie civil", "G"),
    "4664Z": ("Commerce de gros de machines pour l'industrie textile et l'habillement", "G"),
    "4665Z": ("Commerce de gros de mobilier de bureau", "G"),
    "4666Z": ("Commerce de gros d'autres machines et équipements de bureau", "G"),
    "4669A": ("Commerce de gros de matériel électrique", "G"),
    "4669B": ("Commerce de gros de fournitures et équipements industriels divers", "G"),
    "4669C": ("Commerce de gros de fournitures et équipements divers pour le commerce et les services", "G"),
    "4671Z": ("Commerce de gros de combustibles et de produits annexes", "G"),
    "4672Z": ("Commerce de gros de minerais et métaux", "G"),
    "4673A": ("Commerce de gros de bois et de matériaux de construction", "G"),
    "4673B": ("Commerce de gros d'appareils sanitaires et de produits de décoration", "G"),
    "4674A": ("Commerce de gros de quincaillerie", "G"),
    "4674B": ("Commerce de gros de fournitures pour la plomberie et le chauffage", "G"),
    "4675Z": ("Commerce de gros de produits chimiques", "G"),
    "4676Z": ("Commerce de gros d'autres produits intermédiaires", "G"),
    "4677Z": ("Commerce de gros de déchets et débris", "G"),
    "4690Z": ("Commerce de gros non spécialisé", "G"),
    "4711A": ("Commerce de détail de produits surgelés", "G"),
    "4711B": ("Commerce d'alimentation générale", "G"),
    "4711C": ("Supérettes", "G"),
    "4711D": ("Supermarchés", "G"),
    "4711E": ("Magasins multi-commerces", "G"),
    "4711F": ("Hypermarchés", "G"),
    "4719A": ("Grands magasins", "G"),
    "4719B": ("Autres commerces de détail en magasin non spécialisé", "G"),
    "4721Z": ("Commerce de détail de fruits et légumes en magasin spécialisé", "G"),
    "4722Z": ("Commerce de détail de viandes et de produits à base de viande en magasin spécialisé", "G"),
    "4723Z": ("Commerce de détail de poissons, crustacés et mollusques en magasin spécialisé", "G"),
    "4724Z": ("Commerce de détail de pain, pâtisserie et confiserie en magasin spécialisé", "G"),
    "4725Z": ("Commerce de détail de boissons en magasin spécialisé", "G"),
    "4726Z": ("Commerce de détail de produits à base de tabac en magasin spécialisé", "G"),
    "4729Z": ("Autres commerces de détail alimentaires en magasin spécialisé", "G"),
    "4730Z": ("Commerce de détail de carburants en magasin spécialisé", "G"),
    "4741Z": ("Commerce de détail d'ordinateurs, d'unités périphériques et de logiciels en magasin spécialisé", "G"),
    "4742Z": ("Commerce de détail de matériels de télécommunication en magasin spécialisé", "G"),
    "4743Z": ("Commerce de détail de matériels audio et vidéo en magasin spécialisé", "G"),
    "4751Z": ("Commerce de détail de textiles en magasin spécialisé", "G"),
    "4752A": ("Commerce de détail de quincaillerie, peintures et verres en petites surfaces (moins de 400 m²)", "G"),
    "4752B": ("Commerce de détail de quincaillerie, peintures et verres en grandes surfaces", "G"),
    "4753Z": ("Commerce de détail de tapis, moquettes et revêtements de murs et de sols en magasin spécialisé", "G"),
    "4754Z": ("Commerce de détail d'appareils électroménagers en magasin spécialisé", "G"),
    "4759A": ("Commerce de détail de meubles", "G"),
    "4759B": ("Commerce de détail d'autres équipements du foyer", "G"),
    "4761Z": ("Commerce de détail de livres en magasin spécialisé", "G"),
    "4762Z": ("Commerce de détail de journaux et papeterie en magasin spécialisé", "G"),
    "4763Z": ("Commerce de détail d'enregistrements musicaux et vidéo en magasin spécialisé", "G"),
    "4764Z": ("Commerce de détail d'articles de sport en magasin spécialisé", "G"),
    "4765Z": ("Commerce de détail de jeux et jouets en magasin spécialisé", "G"),
    "4771Z": ("Commerce de détail d'habillement en magasin spécialisé", "G"),
    "4772A": ("Commerce de détail de la chaussure", "G"),
    "4772B": ("Commerce de détail de maroquinerie et d'articles de voyage", "G"),
    "4773Z": ("Commerce de détail de produits pharmaceutiques en magasin spécialisé", "G"),
    "4774Z": ("Commerce de détail d'articles médicaux et orthopédiques en magasin spécialisé", "G"),
    "4775Z": ("Commerce de détail de parfumerie et de produits de beauté en magasin spécialisé", "G"),
    "4776Z": ("Commerce de détail de fleurs, plantes, graines, engrais, animaux de compagnie et aliments pour ces animaux en magasin spécialisé", "G"),
    "4777Z": ("Commerce de détail d'articles d'horlogerie et de bijouterie en magasin spécialisé", "G"),
    "4778A": ("Commerces de détail d'optique", "G"),
    "4778B": ("Commerce de détail de charbons et combustibles", "G"),
    "4778C": ("Autres commerces de détail spécialisés divers", "G"),
    "4779Z": ("Commerce de détail de biens d'occasion en magasin", "G"),
    "4781Z": ("Commerce de détail alimentaire sur éventaires et marchés", "G"),
    "4782Z": ("Commerce de détail de textiles, d'habillement et de chaussures sur éventaires et marchés", "G"),
    "4789Z": ("Autres commerces de détail sur éventaires et marchés", "G"),
    "4791A": ("Vente à distance sur catalogue général", "G"),
    "4791B": ("Vente à distance sur catalogue spécialisé", "G"),
    "4799A": ("Vente à domicile", "G"),
    "4799B": ("Vente par automates et autres commerces de détail hors magasin, éventaires ou marchés n.c.a.", "G"),
    # H — Transports
    "4910Z": ("Transport ferroviaire interurbain de voyageurs", "H"),
    "4920Z": ("Transports ferroviaires de fret", "H"),
    "4931Z": ("Transports urbains et suburbains de voyageurs", "H"),
    "4932Z": ("Transports de voyageurs par taxis", "H"),
    "4939A": ("Transports routiers réguliers de voyageurs", "H"),
    "4939B": ("Autres transports routiers de voyageurs", "H"),
    "4941A": ("Transports routiers de fret interurbains", "H"),
    "4941B": ("Transports routiers de fret de proximité", "H"),
    "4941C": ("Location de camions avec chauffeur", "H"),
    "4942Z": ("Services de déménagement", "H"),
    "4950Z": ("Transports par conduites", "H"),
    "5010Z": ("Transports maritimes et côtiers de passagers", "H"),
    "5020Z": ("Transports maritimes et côtiers de fret", "H"),
    "5030Z": ("Transports fluviaux de passagers", "H"),
    "5040Z": ("Transports fluviaux de fret", "H"),
    "5110Z": ("Transports aériens de passagers", "H"),
    "5121Z": ("Transports aériens de fret", "H"),
    "5122Z": ("Transports spatiaux", "H"),
    "5210A": ("Entreposage et stockage frigorifique", "H"),
    "5210B": ("Entreposage et stockage non frigorifique", "H"),
    "5221Z": ("Services auxiliaires des transports terrestres", "H"),
    "5222Z": ("Services auxiliaires des transports par eau", "H"),
    "5223Z": ("Services auxiliaires des transports aériens", "H"),
    "5224A": ("Manutention portuaire", "H"),
    "5224B": ("Manutention non portuaire", "H"),
    "5229A": ("Messagerie, fret express", "H"),
    "5229B": ("Affrètement et organisation des transports", "H"),
    "5310Z": ("Activités de poste dans le cadre d'une obligation de service universel", "H"),
    "5320Z": ("Autres activités de poste et de courrier", "H"),
    # I — Hébergement/restauration
    "5510Z": ("Hôtels et hébergement similaire", "I"),
    "5520Z": ("Hébergement touristique et autre hébergement de courte durée", "I"),
    "5530Z": ("Terrains de camping et parcs pour caravanes ou véhicules de loisirs", "I"),
    "5590Z": ("Autres hébergements", "I"),
    "5610A": ("Restauration traditionnelle", "I"),
    "5610B": ("Cafétérias et autres libres-services", "I"),
    "5610C": ("Restauration de type rapide", "I"),
    "5621Z": ("Services des traiteurs", "I"),
    "5629A": ("Restauration collective sous contrat", "I"),
    "5629B": ("Autres services de restauration n.c.a.", "I"),
    "5630Z": ("Débits de boissons", "I"),
    # J — Information/communication
    "5811Z": ("Édition de livres", "J"),
    "5812Z": ("Édition de répertoires et de fichiers d'adresses", "J"),
    "5813Z": ("Édition de journaux", "J"),
    "5814Z": ("Édition de revues et périodiques", "J"),
    "5819Z": ("Autres activités d'édition", "J"),
    "5821Z": ("Édition de jeux électroniques", "J"),
    "5829A": ("Édition de logiciels système et de réseau", "J"),
    "5829B": ("Édition de logiciels outils de développement et de langages", "J"),
    "5829C": ("Édition de logiciels applicatifs", "J"),
    "5911A": ("Production de films et de programmes pour la télévision", "J"),
    "5911B": ("Production de films institutionnels et publicitaires", "J"),
    "5911C": ("Production de films pour le cinéma", "J"),
    "5912Z": ("Post-production de films cinématographiques, de vidéo et de programmes de télévision", "J"),
    "5913A": ("Distribution de films cinématographiques", "J"),
    "5913B": ("Édition et distribution vidéo", "J"),
    "5914Z": ("Projection de films cinématographiques", "J"),
    "5920Z": ("Enregistrement sonore et édition musicale", "J"),
    "6010Z": ("Édition et diffusion de programmes radio", "J"),
    "6020A": ("Edition de chaînes généralistes", "J"),
    "6020B": ("Edition de chaînes thématiques", "J"),
    "6110Z": ("Télécommunications filaires", "J"),
    "6120Z": ("Télécommunications sans fil", "J"),
    "6130Z": ("Télécommunications par satellite", "J"),
    "6190Z": ("Autres activités de télécommunication", "J"),
    "6201Z": ("Programmation informatique", "J"),
    "6202A": ("Conseil en systèmes et logiciels informatiques", "J"),
    "6202B": ("Tierce maintenance de systèmes et d'applications informatiques", "J"),
    "6203Z": ("Gestion d'installations informatiques", "J"),
    "6209Z": ("Autres activités informatiques", "J"),
    "6311Z": ("Traitement de données, hébergement et activités connexes", "J"),
    "6312Z": ("Portails Internet", "J"),
    "6391Z": ("Activités des agences de presse", "J"),
    "6399Z": ("Autres services d'information n.c.a.", "J"),
    # K — Finance/assurance
    "6411Z": ("Activités de banque centrale", "K"),
    "6419Z": ("Autres intermédiations monétaires", "K"),
    "6420Z": ("Activités des sociétés holding", "K"),
    "6430Z": ("Fonds de placement et entités financières similaires", "K"),
    "6491Z": ("Crédit-bail", "K"),
    "6492Z": ("Autre distribution de crédit", "K"),
    "6499Z": ("Autres activités des services financiers, hors assurance et caisses de retraite, n.c.a.", "K"),
    "6511Z": ("Assurance vie", "K"),
    "6512Z": ("Autres assurances", "K"),
    "6520Z": ("Réassurance", "K"),
    "6530Z": ("Caisses de retraite", "K"),
    "6611Z": ("Administration de marchés financiers", "K"),
    "6612Z": ("Courtage de valeurs mobilières et de marchandises", "K"),
    "6619A": ("Supports juridiques de gestion de patrimoine mobilier", "K"),
    "6619B": ("Autres activités auxiliaires de services financiers, hors assurance et caisses de retraite, n.c.a.", "K"),
    "6621Z": ("Évaluation des risques et dommages", "K"),
    "6622Z": ("Activités des agents et courtiers d'assurances", "K"),
    "6629Z": ("Autres activités auxiliaires d'assurance et de caisses de retraite", "K"),
    "6630Z": ("Gestion de fonds", "K"),
    # L — Immobilier
    "6810Z": ("Activités des marchands de biens immobiliers", "L"),
    "6820A": ("Location de logements", "L"),
    "6820B": ("Location de terrains et d'autres biens immobiliers", "L"),
    "6831Z": ("Agences immobilières", "L"),
    "6832A": ("Administration d'immeubles et autres biens immobiliers", "L"),
    "6832B": ("Supports juridiques de gestion de patrimoine immobilier", "L"),
    # M — Activités spécialisées
    "6910Z": ("Activités juridiques", "M"),
    "6920Z": ("Activités comptables", "M"),
    "7010Z": ("Activités des sièges sociaux", "M"),
    "7021Z": ("Conseil en relations publiques et communication", "M"),
    "7022Z": ("Conseil pour les affaires et autres conseils de gestion", "M"),
    "7111Z": ("Activités d'architecture", "M"),
    "7112A": ("Activité des géomètres", "M"),
    "7112B": ("Ingénierie, études techniques", "M"),
    "7120A": ("Contrôle technique automobile", "M"),
    "7120B": ("Analyses, essais et inspections techniques", "M"),
    "7211Z": ("Recherche-développement en biotechnologie", "M"),
    "7219Z": ("Autre recherche-développement en sciences physiques et naturelles", "M"),
    "7220Z": ("Recherche-développement en sciences humaines et sociales", "M"),
    "7311Z": ("Activités des agences de publicité", "M"),
    "7312Z": ("Régie publicitaire de médias", "M"),
    "7320Z": ("Études de marché et sondages", "M"),
    "7410Z": ("Activités spécialisées de design", "M"),
    "7420Z": ("Activités photographiques", "M"),
    "7430Z": ("Traduction et interprétation", "M"),
    "7490A": ("Activité des économistes de la construction", "M"),
    "7490B": ("Activités spécialisées, scientifiques et techniques diverses", "M"),
    "7500Z": ("Activités vétérinaires", "M"),
    # N — Services administratifs
    "7711A": ("Location de courte durée de voitures et de véhicules automobiles légers", "N"),
    "7711B": ("Location de longue durée de voitures et de véhicules automobiles légers", "N"),
    "7712Z": ("Location et location-bail de camions", "N"),
    "7721Z": ("Location et location-bail d'articles de loisirs et de sport", "N"),
    "7722Z": ("Location de vidéocassettes et disques vidéo", "N"),
    "7729Z": ("Location et location-bail d'autres biens personnels et domestiques", "N"),
    "7731Z": ("Location et location-bail de machines et équipements agricoles", "N"),
    "7732Z": ("Location et location-bail de machines et équipements pour la construction", "N"),
    "7733Z": ("Location et location-bail de machines de bureau et de matériel informatique", "N"),
    "7734Z": ("Location et location-bail de matériels de transport par eau", "N"),
    "7735Z": ("Location et location-bail de matériels de transport aérien", "N"),
    "7739Z": ("Location et location-bail d'autres machines, équipements et biens matériels n.c.a.", "N"),
    "7740Z": ("Location-bail de propriété intellectuelle et de produits similaires, à l'exception des œuvres soumises à copyright", "N"),
    "7810Z": ("Activités des agences de placement de main-d'œuvre", "N"),
    "7820Z": ("Activités des agences de travail temporaire", "N"),
    "7830Z": ("Autre mise à disposition de ressources humaines", "N"),
    "7911Z": ("Activités des agences de voyage", "N"),
    "7912Z": ("Activités des voyagistes", "N"),
    "7990Z": ("Autres services de réservation et activités connexes", "N"),
    "8010Z": ("Activités de sécurité privée", "N"),
    "8020Z": ("Activités liées aux systèmes de sécurité", "N"),
    "8030Z": ("Activités d'enquête", "N"),
    "8110Z": ("Activités combinées de soutien lié aux bâtiments", "N"),
    "8121Z": ("Nettoyage courant des bâtiments", "N"),
    "8122Z": ("Autres activités de nettoyage des bâtiments et nettoyage industriel", "N"),
    "8129A": ("Désinfection, désinsectisation, dératisation", "N"),
    "8129B": ("Autres activités de nettoyage n.c.a.", "N"),
    "8130Z": ("Services d'aménagement paysager", "N"),
    "8211Z": ("Services administratifs combinés de bureau", "N"),
    "8219A": ("Photocopie", "N"),
    "8219B": ("Saisie de données", "N"),
    "8220Z": ("Activités de centres d'appels", "N"),
    "8230Z": ("Organisation de foires, salons professionnels et congrès", "N"),
    "8291Z": ("Activités des agences de recouvrement de factures et des sociétés d'information financière sur la clientèle", "N"),
    "8292Z": ("Activités de conditionnement", "N"),
    "8299Z": ("Autres activités de soutien aux entreprises n.c.a.", "N"),
    # O — Administration publique
    "8411Z": ("Administration publique générale", "O"),
    "8412Z": ("Tutelle des activités économiques", "O"),
    "8413Z": ("Tutelle des activités sociales", "O"),
    "8421Z": ("Affaires étrangères", "O"),
    "8422Z": ("Défense", "O"),
    "8423Z": ("Justice", "O"),
    "8424Z": ("Activités d'ordre public et de sécurité", "O"),
    "8425Z": ("Services du feu et de secours", "O"),
    "8430A": ("Activités générales de sécurité sociale", "O"),
    "8430B": ("Gestion des retraites complémentaires", "O"),
    "8430C": ("Distribution sociale de revenus", "O"),
    # P — Enseignement
    "8510Z": ("Enseignement pré-primaire", "P"),
    "8520Z": ("Enseignement primaire", "P"),
    "8531Z": ("Enseignement secondaire général", "P"),
    "8532Z": ("Enseignement secondaire technique ou professionnel", "P"),
    "8541Z": ("Enseignement post-secondaire non supérieur", "P"),
    "8542Z": ("Enseignement supérieur", "P"),
    "8551Z": ("Enseignement de disciplines sportives et d'activités de loisirs", "P"),
    "8552Z": ("Enseignement culturel", "P"),
    "8553Z": ("Enseignement de la conduite", "P"),
    "8559A": ("Formation continue d'adultes", "P"),
    "8559B": ("Autres enseignements", "P"),
    "8560Z": ("Activités de soutien à l'enseignement", "P"),
    # Q — Santé/social
    "8610Z": ("Activités hospitalières", "Q"),
    "8621Z": ("Activité des médecins généralistes", "Q"),
    "8622A": ("Activités de radiodiagnostic et de radiothérapie", "Q"),
    "8622B": ("Activités chirurgicales", "Q"),
    "8622C": ("Autres activités des médecins spécialistes", "Q"),
    "8623Z": ("Pratique dentaire", "Q"),
    "8690A": ("Ambulances", "Q"),
    "8690B": ("Laboratoires d'analyses médicales", "Q"),
    "8690C": ("Centres de collecte et banques d'organes", "Q"),
    "8690D": ("Activités des infirmiers et des sages-femmes", "Q"),
    "8690E": ("Activités des professionnels de la rééducation, de l'appareillage et des pédicures-podologues", "Q"),
    "8690F": ("Activités de santé humaine non classées ailleurs", "Q"),
    "8710A": ("Hébergement médicalisé pour personnes âgées", "Q"),
    "8710B": ("Hébergement médicalisé pour enfants handicapés", "Q"),
    "8710C": ("Hébergement médicalisé pour adultes handicapés et autre hébergement médicalisé", "Q"),
    "8720A": ("Hébergement social pour handicapés mentaux et malades mentaux", "Q"),
    "8720B": ("Hébergement social pour toxicomanes", "Q"),
    "8730A": ("Hébergement social pour personnes âgées", "Q"),
    "8730B": ("Hébergement social pour handicapés physiques", "Q"),
    "8790A": ("Hébergement social pour enfants en difficultés", "Q"),
    "8790B": ("Hébergement social pour adultes et familles en difficultés", "Q"),
    "8810A": ("Aide à domicile", "Q"),
    "8810B": ("Accueil ou accompagnement sans hébergement d'adultes handicapés ou de personnes âgées", "Q"),
    "8810C": ("Aide par le travail", "Q"),
    "8891A": ("Accueil de jeunes enfants", "Q"),
    "8891B": ("Accueil ou accompagnement sans hébergement d'enfants handicapés", "Q"),
    "8899A": ("Autre accueil ou accompagnement sans hébergement d'enfants et d'adolescents", "Q"),
    "8899B": ("Action sociale sans hébergement n.c.a.", "Q"),
    # R — Arts/spectacles
    "9001Z": ("Arts du spectacle vivant", "R"),
    "9002Z": ("Activités de soutien au spectacle vivant", "R"),
    "9003A": ("Création artistique relevant des arts plastiques", "R"),
    "9003B": ("Autre création artistique", "R"),
    "9004Z": ("Gestion de salles de spectacles", "R"),
    "9101Z": ("Gestion des bibliothèques et des archives", "R"),
    "9102Z": ("Gestion des musées", "R"),
    "9103Z": ("Gestion des sites et monuments historiques et des attractions touristiques similaires", "R"),
    "9104Z": ("Gestion des jardins botaniques et zoologiques et des réserves naturelles", "R"),
    "9200Z": ("Organisation de jeux de hasard et d'argent", "R"),
    "9311Z": ("Gestion d'installations sportives", "R"),
    "9312Z": ("Activités de clubs de sports", "R"),
    "9313Z": ("Activités des centres de culture physique", "R"),
    "9319Z": ("Autres activités liées au sport", "R"),
    "9321Z": ("Activités des parcs d'attractions et parcs à thèmes", "R"),
    "9329Z": ("Autres activités récréatives et de loisirs", "R"),
    # S — Autres services
    "9411Z": ("Activités des organisations patronales et consulaires", "S"),
    "9412Z": ("Activités des organisations professionnelles", "S"),
    "9420Z": ("Activités des syndicats de salariés", "S"),
    "9491Z": ("Activités des organisations religieuses", "S"),
    "9492Z": ("Activités des organisations politiques", "S"),
    "9499Z": ("Autres organisations fonctionnant par adhésion volontaire", "S"),
    "9511Z": ("Réparation d'ordinateurs et d'équipements périphériques", "S"),
    "9512Z": ("Réparation d'équipements de communication", "S"),
    "9521Z": ("Réparation de produits électroniques grand public", "S"),
    "9522Z": ("Réparation d'appareils électroménagers et d'équipements pour la maison et le jardin", "S"),
    "9523Z": ("Réparation de chaussures et d'articles en cuir", "S"),
    "9524Z": ("Réparation de meubles et d'équipements du foyer", "S"),
    "9525Z": ("Réparation d'articles d'horlogerie et de bijouterie", "S"),
    "9529Z": ("Réparation d'autres biens personnels et domestiques", "S"),
    "9601A": ("Blanchisserie-teinturerie de gros", "S"),
    "9601B": ("Blanchisserie-teinturerie de détail", "S"),
    "9602A": ("Coiffure", "S"),
    "9602B": ("Soins de beauté", "S"),
    "9603Z": ("Services funéraires", "S"),
    "9604Z": ("Entretien corporel", "S"),
    "9609Z": ("Autres services personnels n.c.a.", "S"),
    # T — Ménages employeurs
    "9700Z": ("Activités des ménages en tant qu'employeurs de personnel domestique", "T"),
    "9810Z": ("Activités indifférenciées des ménages en tant que producteurs de biens pour usage propre", "T"),
    "9820Z": ("Activités indifférenciées des ménages en tant que producteurs de services pour usage propre", "T"),
    # U — Extra-territoriaux
    "9900Z": ("Activités des organisations et organismes extraterritoriaux", "U"),
}


def _lookup(code: str) -> dict | None:
    code = code.upper().strip()
    if code in NAF:
        libelle, section = NAF[code]
        return {
            "code": code,
            "libelle": libelle,
            "section": section,
            "section_libelle": SECTIONS[section],
        }
    return None


def _search(query: str, limit: int = 20) -> list[dict]:
    q = query.lower().strip()
    results = []
    for code, (libelle, section) in NAF.items():
        if q in libelle.lower() or q in code.lower():
            results.append({
                "code": code,
                "libelle": libelle,
                "section": section,
                "section_libelle": SECTIONS[section],
            })
            if len(results) >= limit:
                break
    return results


def _make_402(host: str, endpoint: str = "/code/{code}") -> JSONResponse:
    return JSONResponse(
        status_code=402,
        content={
            "x402Version": 1, "error": "Payment required",
            "accepts": [{
                "scheme": "exact", "network": NETWORK,
                "maxAmountRequired": PRICE_ATOMIC,
                "resource": f"https://{host}/search",
                "description": "Lookup code NAF/APE INSEE 2008 Rév. 2",
                "mimeType": "application/json",
                "payTo": PAY_TO, "maxTimeoutSeconds": 300,
                "asset": ASSET_ADDRESS, "extra": {"name": "USDC", "version": "2"},
            }],
        },
        headers={"Access-Control-Allow-Origin": "*", "Cache-Control": "no-store",
                 "Access-Control-Expose-Headers": "X-PAYMENT-RESPONSE"},
    )


@app.middleware("http")
async def x402_middleware(request: Request, call_next):
    path = request.url.path
    is_paid = (
        (path.startswith("/code/") and request.method == "GET") or
        (path == "/search" and request.method == "GET")
    )
    if is_paid:
        if not (request.headers.get("X-PAYMENT") or request.headers.get("x-payment")):
            return _make_402(request.headers.get("host", "x402-naf.suretat.com"), path)
    return await call_next(request)


@app.get("/")
def root():
    return {
        "service": "x402 NAF/APE Code Lookup",
        "protocol": "x402 (Base/USDC)",
        "price": f"{int(PRICE_ATOMIC)/1_000_000} USDC/appel",
        "endpoints": {
            "GET /code/{code}": "Lookup d'un code NAF (ex: 6201Z)",
            "GET /search?q=...&limit=20": "Recherche par mot-clé dans les libellés",
            "GET /sections": "Liste des 21 sections NAF (gratuit)",
        },
        "codes_count": len(NAF),
        "source": "INSEE NAF 2008 Rév. 2",
        "docs": "/docs",
    }


@app.get("/sections")
def get_sections():
    return {"sections": [{"code": k, "libelle": v} for k, v in SECTIONS.items()]}


@app.get("/code/{code}")
def get_code(code: str, request: Request):
    stats["total_paid"] += 1
    stats["revenue_usdc"] += int(PRICE_ATOMIC) / 1_000_000
    result = _lookup(code)
    if not result:
        return JSONResponse(status_code=404, content={
            "error": f"Code NAF '{code.upper()}' introuvable",
            "hint": "Vérifiez le format (ex: 6201Z) ou utilisez /search",
        })
    return result


@app.get("/search")
def search(request: Request, q: str = Query(..., min_length=2), limit: int = Query(default=20, ge=1, le=100)):
    stats["total_paid"] += 1
    stats["revenue_usdc"] += int(PRICE_ATOMIC) / 1_000_000
    results = _search(q, limit)
    return {"query": q, "count": len(results), "results": results}


@app.get("/.well-known/x402.json")
async def x402_well_known(request: Request):
    host = request.headers.get("host", "x402-naf.suretat.com")
    return {"x402Version": 1, "accepts": [{
        "scheme": "exact", "network": NETWORK, "maxAmountRequired": PRICE_ATOMIC,
        "resource": f"https://{host}/search",
        "description": "Lookup code NAF/APE INSEE 2008 Rév. 2",
        "mimeType": "application/json", "payTo": PAY_TO, "maxTimeoutSeconds": 300,
        "asset": ASSET_ADDRESS, "extra": {"name": "USDC", "version": "2"},
    }]}


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/stats")
def get_stats():
    return {**stats, "uptime_seconds": int(time.time() - stats["start_time"])}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=3089, proxy_headers=True, forwarded_allow_ips="*")
