name: x402-num2words

services:
  num2words:
    build: .
    container_name: x402-num2words
    restart: unless-stopped
    ports:
      - "3044:3044"
    env_file:
      - .env
    networks:
      - traefik
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x402-num2words.rule=Host(`x402-num2words.suretat.com`)"
      - "traefik.http.routers.x402-num2words.entrypoints=websecure"
      - "traefik.http.routers.x402-num2words.tls.certresolver=letsencrypt"
      - "traefik.http.services.x402-num2words.loadbalancer.server.port=3044"

networks:
  traefik:
    external: true
    name: traefik
  proxy:
    external: true
    name: proxy
