name: x402-geocoder-fr

services:
  geocoder:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: x402-geocoder-fr
    restart: unless-stopped
    ports:
      - "3035:3035"
    environment:
      - PORT=3035
      - DATA_FILE=/app/data/stats.json
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - traefik
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x402-geocoder.rule=Host(`x402-geocoder.suretat.com`)"
      - "traefik.http.routers.x402-geocoder.entrypoints=websecure"
      - "traefik.http.routers.x402-geocoder.tls.certresolver=letsencrypt"
      - "traefik.http.services.x402-geocoder.loadbalancer.server.port=3035"

networks:
  traefik:
    external: true
    name: traefik
  proxy:
    external: true
    name: proxy
