name: x402-image-resize

services:
  image_resize:
    build: .
    container_name: x402-image-resize
    restart: unless-stopped
    ports:
      - "3076:3076"
    env_file:
      - .env
    networks:
      - traefik
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x402-image-resize.rule=Host(`x402-image-resize.suretat.com`)"
      - "traefik.http.routers.x402-image-resize.entrypoints=websecure"
      - "traefik.http.routers.x402-image-resize.tls.certresolver=letsencrypt"
      - "traefik.http.services.x402-image-resize.loadbalancer.server.port=3076"

networks:
  traefik:
    external: true
    name: traefik
  proxy:
    external: true
    name: proxy
