name: x402-ssl

services:
  ssl:
    build: .
    container_name: x402-ssl
    restart: unless-stopped
    ports:
      - "3078:3078"
    env_file:
      - .env
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
