name: x402-ssl

services:
  ssl:
    build: .
    container_name: x402-ssl
    restart: unless-stopped
    ports:
      - "3078:3078"
    env_file:
      - .env
    networks:
      - traefik
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x402-ssl.rule=Host(`x402-ssl.suretat.com`)"
      - "traefik.http.routers.x402-ssl.entrypoints=websecure"
      - "traefik.http.routers.x402-ssl.tls.certresolver=letsencrypt"
      - "traefik.http.services.x402-ssl.loadbalancer.server.port=3078"

networks:
  traefik:
    external: true
    name: traefik
  proxy:
    external: true
    name: proxy
