name: x402-translate-fr

services:
  translate:
    build: .
    container_name: x402-translate-fr
    restart: unless-stopped
    ports:
      - "3037:3037"
    env_file:
      - .env
    networks:
      - traefik
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x402-translate-fr.rule=Host(`x402-translate-fr.suretat.com`)"
      - "traefik.http.routers.x402-translate-fr.entrypoints=websecure"
      - "traefik.http.routers.x402-translate-fr.tls.certresolver=letsencrypt"
      - "traefik.http.services.x402-translate-fr.loadbalancer.server.port=3037"

networks:
  traefik:
    external: true
    name: traefik
  proxy:
    external: true
    name: proxy
