name: x402-iban

services:
  iban:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: x402-iban
    restart: unless-stopped
    ports:
      - "3032:3032"
    environment:
      - PORT=3032
      - DATA_FILE=/app/data/stats.json
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - traefik
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x402-iban.rule=Host(`x402-iban.suretat.com`)"
      - "traefik.http.routers.x402-iban.entrypoints=websecure"
      - "traefik.http.routers.x402-iban.tls.certresolver=letsencrypt"
      - "traefik.http.services.x402-iban.loadbalancer.server.port=3032"

networks:
  traefik:
    external: true
    name: traefik
  proxy:
    external: true
    name: proxy
