name: x402-qrcode

services:
  qrcode:
    build: .
    container_name: x402-qrcode
    restart: unless-stopped
    ports:
      - "3042:3042"
    env_file:
      - .env
    networks:
      - traefik
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x402-qrcode.rule=Host(`x402-qrcode.suretat.com`)"
      - "traefik.http.routers.x402-qrcode.entrypoints=websecure"
      - "traefik.http.routers.x402-qrcode.tls.certresolver=letsencrypt"
      - "traefik.http.services.x402-qrcode.loadbalancer.server.port=3042"

networks:
  traefik:
    external: true
    name: traefik
  proxy:
    external: true
    name: proxy
