name: x402-hash

services:
  hash:
    build: .
    container_name: x402-hash
    restart: unless-stopped
    ports:
      - "3046:3046"
    env_file:
      - .env
    networks:
      - traefik
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x402-hash.rule=Host(`x402-hash.suretat.com`)"
      - "traefik.http.routers.x402-hash.entrypoints=websecure"
      - "traefik.http.routers.x402-hash.tls.certresolver=letsencrypt"
      - "traefik.http.services.x402-hash.loadbalancer.server.port=3046"

networks:
  traefik:
    external: true
    name: traefik
  proxy:
    external: true
    name: proxy
