name: x402-ipgeo

services:
  ipgeo:
    build: .
    container_name: x402-ipgeo
    restart: unless-stopped
    ports:
      - "3043:3043"
    env_file:
      - .env
    networks:
      - traefik
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x402-ipgeo.rule=Host(`x402-ipgeo.suretat.com`)"
      - "traefik.http.routers.x402-ipgeo.entrypoints=websecure"
      - "traefik.http.routers.x402-ipgeo.tls.certresolver=letsencrypt"
      - "traefik.http.services.x402-ipgeo.loadbalancer.server.port=3043"

networks:
  traefik:
    external: true
    name: traefik
  proxy:
    external: true
    name: proxy
