name: x402-urlmeta

services:
  urlmeta:
    build: .
    container_name: x402-urlmeta
    restart: unless-stopped
    ports:
      - "3047:3047"
    env_file:
      - .env
    networks:
      - traefik
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x402-urlmeta.rule=Host(`x402-urlmeta.suretat.com`)"
      - "traefik.http.routers.x402-urlmeta.entrypoints=websecure"
      - "traefik.http.routers.x402-urlmeta.tls.certresolver=letsencrypt"
      - "traefik.http.services.x402-urlmeta.loadbalancer.server.port=3047"

networks:
  traefik:
    external: true
    name: traefik
  proxy:
    external: true
    name: proxy
